name: learn
on: [push]
#  push:
#    branches:
#      - main
#      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install
      - run: node index.js
      - name: try to push a new file to the repo
        run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add generated.txt
          git commit -m "update generated"
          git push
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: web # The folder the action should deploy.
